### ISSUE TITLE
Cannot change to line placement mode

### ISSUE THREAD

**Issue by CameronFowlks** [kremnev8/CoreKeeperMods#2]
Hey, I am unable to change from square placement to line placement. I think the problem is the fact that my keybind for map was already set to C, so when I installed the mod I feel like maybe it got permanently overwritten? I've tried rebooting the game after rebinding map back to M with no luck.

**Comment by limoka** [comment]
Please try resetting keybinds or manually setting the keybinds.

**Comment by limoka** [comment]
Also make sure you see custom keybinds in the controls section. If you don't please check your installation.

**Comment by CameronFowlks** [comment]
Ah, terribly sorry, I didn't realize there were custom binds in the controls menu.
