### ISSUE TITLE
SUGGESTION: Allow placing of blocks to replace the blocks underneath them.

### ISSUE THREAD

**Issue by KosmosisDire** [kremnev8/CoreKeeperMods#4]
First of all the placement mod is simply amazing, thank you for making it!

I often want to replace blocks, floors, or ground which means that I have to dig up or break all the blocks that are currently in that position. I think it would be great if there was a key you could hold that would break all the blocks / floors (depending on what you were placing) that were underneath the placement, before placing the new blocks down. This would make it much faster to replace floors, walls, or grounds with different kinds of floors, walls, and grounds.

**Comment by limoka** [comment]
Thanks for suggestion. I will look into implementing this when I have time.

**Comment by KosmosisDire** [comment]
Would you be willing to accept PRs? (Not that I would definitely do this, but I might have the time and motivation to tackle it)

**Comment by limoka** [comment]
Yes. I will probably check if it actually works and stuff, but generally yes.

**Comment by limoka** [comment]
Added in v1.5.0 and corrected for walls in v1.5.1
