### ISSUE TITLE
Customize keybindings

### ISSUE THREAD

**Issue by j-perezr** [kremnev8/CoreKeeperMods#8]
Hi!
first of all, thank you very much for your mod! ^^
Unafortunatelly I don't have numpad in my keyboard making it impossible for me to use your mod :( 
Would it be possible to configure keybindings? please :) Or to have additional bindings, for example, page up and page down to increase the size

**Comment by limoka** [comment]
This is already a feature. Please read the README better. Go to your options.

**Comment by j-perezr** [comment]
Apologies,
Which options menu? I installed the mod using thunderstore mod manager and in the options menu of the mod manager I don't see how to re bind them.

**Comment by limoka** [comment]
Options ingame. The same place you would rebind vanilla keybinds

**Comment by j-perezr** [comment]
Thank you
